### ISSUE TITLE
Delete MainActivity

### ISSUE THREAD

**Issue by benwaffle** [wiiam/srht-android#2]

**Comment by wiiaam** [comment]
fine
https://github.com/wiiam/srht-android/commit/f3f436621340dce417b6005ba36443e0eb010f58

**Comment by benwaffle** [comment]
Did you test it? i think you might need `<category android:name="android.intent.category.DEFAULT" />` to start from a launcher

**Comment by wiiaam** [comment]
You mean android.intent.category.LAUNCHER? ApiSetup was already set to that
https://github.com/wiiam/srht-android/blob/master/app/src/main/AndroidManifest.xml#L34
And yeah i tested it
